module.exports = {
  extends: ['@commitlint/config-conventional'],
  
  // Ignore automated commits - commitlint will skip validation for these patterns
  ignores: [
    (message) => {
      // Clean the message by taking only the first line and trimming
      const cleanMessage = message.split('\n')[0].trim();
      
      const patterns = [
        /^Merge pull request #\d+/,
        /^Initial plan$/,
        /^chore\(release\):/,
        /^Merge branch/,
        /^\d+\.\d+\.\d+$/,
        /^v\d+\.\d+\.\d+$/,
        /^Revert/,
        /^Auto-generated by/,
        /^Bump/,
        /^Update.*dependabot/
      ];
      
      return patterns.some(pattern => pattern.test(cleanMessage));
    }
  ],
  
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs', 
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert'
      ]
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'subject-max-length': [2, 'always', 100],
    'body-max-line-length': [2, 'always', 200],
    'header-max-length': [2, 'always', 100],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
  }
};