name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: gallis-gh-runner
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'gallis-local/mcp-outline'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Install Github CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
          	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
          	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
          	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
          	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          	&& sudo apt update \
          	&& sudo apt install gh -y
      - name: Enable auto-merge for Dependabot PRs (minor only)
        if: contains(steps.metadata.outputs.update-type, 'version-update:semver-minor') || contains(steps.metadata.outputs.update-type, 'version-update:semver-patch')
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
